create table NEWS_SITE (
    ID uuid,
    VERSION integer not null,
    CREATE_TS timestamp,
    CREATED_BY varchar(50),
    UPDATE_TS timestamp,
    UPDATED_BY varchar(50),
    DELETE_TS timestamp,
    DELETED_BY varchar(50),
    --
    NAME varchar(255),
    URL varchar(255),
    TYPE_ integer,
    CONTENT_TYPE integer,
    FEED_TAG varchar(255),
    FEED_CLASS varchar(255),
    CHANNEL_TAG varchar(255),
    CHANNEL_CLASS_NAME varchar(255),
    ITEM_CLASS varchar(255),
    ITEM_TAG varchar(255),
    TITLE_CLASS varchar(255),
    TITLE_TAG varchar(255),
    DESCRIPTION_CLASS varchar(255),
    DESCRIPTION_TAG varchar(255),
    PUBLISHED_DATE_CLASS varchar(255),
    PUBLISHED_DATE_TAG varchar(255),
    LINK_CLASS varchar(255),
    LINK_TAG varchar(255),
    --
    primary key (ID)
);
